server:
  port: 8001
spring:
  application:
    name: cloud-payment-hystrix-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver   #mysql驱动包
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
eureka:
  client:
    register-with-eureka: true  # 表示是否将自己注册进 Eureka的服务中心 默认为true
    fetch-registry: true # 检索 服务中心 的其它服务 是否从EurekaServer抓取已有的注册信息，默认为true 单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/   #集群版
      defaultZone: http://eureka7001.com:7001/eureka/  # 单机版